server:
  port: 8091
spring:
  application:
    name: sentinel-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启以服务id去注册中心上获取转发地址
      routes:
        - id: baidu
          uri: lb://member-service #转发http://www.baidu.com/
          filters:
            - StripPrefix=1
          predicates:
            - Path=/baidu/**   #匹配规则
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080   #界面访问接口
        port: 8719 #默认  通讯接口
      eager: true
      datasource:
        ds:
          nacos:
            ### nacos连接地址
            server-addr: localhost:8848
            ## nacos连接的分组
            group-id: DEFAULT_GROUP
            ###路由存储规则
            rule-type: flow
            ### 读取配置文件的 data-id
            data-id: gateway-sentinel-ants
            ###  读取培训文件类型为json
            data-type: json



