server:
  port: 81
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让n  acos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启以服务id去注册中心上获取转发地址
      routes:
        - id: baidu
          uri: http://www.baidu.com/ #转发http://www.baidu.com/
          predicates:
            - Path=/bd/**   #匹配规则
        - id: member
          uri: lb://member-service #转发http://www.baidu.com/
          filters:
            - StripPrefix=1
          predicates:
            - Path=/member/**   #匹配规则
  #127.0.0.1/bd   转发到http://www.baidu.com/
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080   #界面访问接口
        port: 8719 #默认  通讯接口
      eager: true
#      datasource:
#        ds:
#          nacos:
#            ### nacos连接地址
#            server-addr: localhost:8848
#            ## nacos连接的分组
#            group-id: DEFAULT_GROUP
#            ###路由存储规则
#            rule-type: flow
#            ### 读取配置文件的 data-id
#            data-id: gateway-sentinel
#            ###  读取培训文件类型为json
#            data-type: json
  datasource:
      url: jdbc:mysql://139.196.30.186:3306/gateway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: lvym
      password: tbny1312
      driver-class-name: com.mysql.cj.jdbc.Driver


